### ISSUE TITLE
Erosion Analysis 

### ISSUE THREAD

**Issue by mortis4567** [NOAA-OCM/QNSPECT#120]
### Latest QNSPECT version

- [X] I am running the latest QNSPECT version

### Similar issues do not exist

- [X] I have searched existing issues to make sure a similar issue does not exist

### What is the bug or the crash?

Errorcode at the end of Calculation.

Tells me : Cannot execute algorithm
Could not load source layer for INPUT_B: C:/Users/Computer/AppData/Local/Temp/processing_beRrmq/0534916b6be34c3f9653e5401940bc64/OUTPUT.tif not found
Cannot execute algorithm
Could not load source layer for INPUT_B: C:/Users/Computer/AppData/Local/Temp/processing_beRrmq/0534916b6be34c3f9653e5401940bc64/OUTPUT.tif not found
Execution failed after 10.08 seconds

Not exactly, since is translated.

I guess some of my Data is not in the right format or something. 

### Versions

GIS-Version | 3.32.3-Lima

**Comment by mortis4567** [comment]
Fixed it myself

**Comment by mortis4567** [comment]
fixed

**Comment by ar-siddiqui** [comment]
> Fixed it myself

@mortis4567 Can you provide details on how you fixed it, if you updated the code, please provide the solution here as well for others.

**Comment by mortis4567** [comment]
some of the Raster layer had different height than the others, was a silly mistake but left me sleepless for days
