### ISSUE TITLE
New values from Modify Land Use not automatically displayed

### ISSUE THREAD

**Issue by idtodd** [NOAA-OCM/QNSPECT#18]
When using Modify Land Use to add a new value to a raster, if the new value is outside the range of the original raster (e.g., '30' is added to a raster with values between '0' and '29'), the new value will not be displayed by default. This bug is present in QGIS when running the "Rasterize (Overwrite With Attribute)" tool.

**Comment by ar-siddiqui** [comment]
When fixing this, the output display name must be fixed as well.
![image](https://user-images.githubusercontent.com/53625184/140955594-038b4e77-ef74-44df-8bed-ce382787cf07.png)

**Comment by ar-siddiqui** [comment]
Helpful links to look at later

https://qgis.org/pyqgis/master/core/QgsRasterFileWriter.html?highlight=rasterfilewriter#module-QgsRasterFileWriter
https://qgis.org/pyqgis/master/core/QgsProcessingParameterRasterDestination.html?highlight=qgsprocessingparameterrasterdestination#qgis.core.QgsProcessingParameterRasterDestination.toOutputDefinition

**Comment by ar-siddiqui** [comment]
QGIS has made a commit that may fix this issue
https://github.com/alexbruy/QGIS/commit/8621721556b0995bd1370f1ec3ec46813e8cf4fb

**Comment by ar-siddiqui** [comment]
> QGIS has made a commit that may fix this issue [alexbruy/QGIS@8621721](https://github.com/alexbruy/QGIS/commit/8621721556b0995bd1370f1ec3ec46813e8cf4fb)

Need investigation if this is still an issue.

**Comment by ar-siddiqui** [comment]
@DaveEslinger I am no longer encountering this issue on QGIS LTR 3.22.4. QGIS has fixed it per the issue we filed. Can you confirm this is not happening anymore? If that is the case, then let's close this.

**Comment by DaveEslinger** [comment]
I can confirm this is no longer an issue.  QGIS LTR 3.22.6.  Let's close it.
