### ISSUE TITLE
Comparison outputs results have weird values

### ISSUE THREAD

**Issue by ar-siddiqui** [NOAA-OCM/QNSPECT#37]
For example, the percent comparison here.
![image](https://user-images.githubusercontent.com/53625184/152369652-f5155e2c-498d-47e5-b2ae-8e28e6bb721a.png)

My first guess is, it is because of no data values, and edges. 

One possible solution is to set the output value as no data value if any of the base rasters have no data value.

This error message might be related to that
![image](https://user-images.githubusercontent.com/53625184/152369481-ef57e8c7-60cd-401c-997c-39890b4cf94d.png)

**Comment by ar-siddiqui** [comment]
If it is not a bug then we may have to style it in a relative manner, like quantile-based styling.

**Comment by NSPECT** [comment]
If any of the compared cells are NA, then the result should be NA.  I can confirm this behavior.

**Comment by ar-siddiqui** [comment]
Fixed in #109
