### ISSUE TITLE
LS Factor calculations are SFD but Flow Accumulation provides MFD option

### ISSUE THREAD

**Issue by ar-siddiqui** [NOAA-OCM/QNSPECT#46]
It needs to be investigated that if LS Factor are always SFD, then does it make scientific sense to have MFD Flow accumulation?

If not, then the MFD option should be removed from `Run Erosion Analysis` tool until #45 is fixed.

**Comment by ar-siddiqui** [comment]
@DaveEslinger can you please investigate if having other calculation in MFD but LS Factor in SFD provides any value to the user / make scientific sense.

**Comment by NSPECT** [comment]
Should be closed by PR #89
