### ISSUE TITLE
Should units of outputs be per year?

### ISSUE THREAD

**Issue by ar-siddiqui** [NOAA-OCM/QNSPECT#66]
Should the units of outputs be per year, like kg/year, L/year etc? This may tell more about the outputs of the results and provide context. @DaveEslinger @NSPECT thoughts?

**Comment by jamie-carter** [comment]
Agree, this would be good to implement so that the units are included in the layer name. I noticed this with the Runoff layers specifically.

**Comment by ar-siddiqui** [comment]
> Should the units of outputs be per year, like kg/year, L/year etc? This may tell more about the outputs of the results. @DaveEslinger @NSPECT thoughts?



> Should the units of outputs be per year, like kg/year, L/year etc? This may tell more about the outputs of the results. @DaveEslinger @NSPECT thoughts?

@DaveEslinger @NSPECT what do you think about this.

**Comment by ar-siddiqui** [comment]
> Should the units of outputs be per year, like kg/year, L/year etc? This may tell more about the outputs of the results. @DaveEslinger @NSPECT thoughts?



> Should the units of outputs be per year, like kg/year, L/year etc? This may tell more about the outputs of the results. @DaveEslinger @NSPECT thoughts?

@DaveEslinger @NSPECT what do you think about this.

**Comment by DaveEslinger** [comment]
Hmm, sorry, I thought I responded to this.  Yes, let's do that.  There is a use case where it would not be desirable (someone does a one event pollutant run), but I think the more common use case is to do annual runs.

**Comment by NSPECT** [comment]
We should close #66, this has been addressed in PR #92.
