### ISSUE TITLE
Grouping error when modifying and rerunning a pollutant analysis.

### ISSUE THREAD

**Issue by NSPECT** [NOAA-OCM/QNSPECT#69]
When making a modification to a pollutant run, the new results do not get loaded into a group.  They just end up wherever the current focused layer is.  This occurs even when changing the name of the run, which would be the name of the group, and when putting them in a new upper level directory.  Closing the Run Pollutant window and reopening a new one, then running also gives this issue.  I am only getting proper grouping with the first run in a QGIS session.

Note that they DO get put into the correct directory.

Below is the logfile result that seems to indicate where the error occurs.  This error occurs when rerunning, but not on a new run.

<SNIP>
GDAL command:
gdal_calc.bat --overwrite --calc "(A / 1000000)" --format GTiff --type Float32 --NoDataValue -9999.0 -A C:\Users\davee\AppData\Local\Temp\processing_zaDTNd\8301b5c072934925930b1cc27f1654f4\accumulation.tif --A_band 1 --outfile "E:\\GIS\\QNSPECT\\100x99x1\\Feb21\\Debug3_run_100cmx1rd\\poll_1 Accumulated.tif"
GDAL command output:
0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90.. 100 - Done
Process completed successfully
Results: {'OUTPUT': 'E:\\GIS\\QNSPECT\\100x99x1\\Feb21\\Debug3_run_100cmx1rd\\poll_1 Accumulated.tif'}
Traceback (most recent call last):
File "C:\Users/davee/AppData/Roaming/QGIS/QGIS3\profiles\Test/python/plugins\QNSPECT\qnspect_run_algorithm.py", line 82, in postProcessAlgorithm
index = parent.children()(selected_nodes[0])
TypeError: 'list' object is not callable

Execution completed in 13.29 seconds
Results:
{'Runoff Accumulated': 'E:\\GIS\\QNSPECT\\100x99x1\\Feb21\\Debug3_run_100cmx1rd\\Runoff '
'Accumulated.tif',
'Runoff Local': 'E:\\GIS\\QNSPECT\\100x99x1\\Feb21\\Debug3_run_100cmx1rd\\Runoff '
'Local.tif',
'poll_1 Accumulated': 'E:\\GIS\\QNSPECT\\100x99x1\\Feb21\\Debug3_run_100cmx1rd\\poll_1 '
'Accumulated.tif',
'poll_1 Local': 'E:\\GIS\\QNSPECT\\100x99x1\\Feb21\\Debug3_run_100cmx1rd\\poll_1 '
'Local.tif'}

Loading resulting layers
Algorithm 'Run Pollution Analysis' finished

**Comment by ar-siddiqui** [comment]
Are you using the latest version of QNSPECT?

**Comment by NSPECT** [comment]
Yes.  Can you reproduce this error?  I thought this worked previously, but it started acting up now.  Note that I'm using a symbolic link from my plugins directory to the git repo. I don't think that should affect anything, but maybe.

**Comment by ar-siddiqui** [comment]
From the error message, I can see that this is not the latest QNSPECT. Can you check it one more time?

**Comment by NSPECT** [comment]
Well, that is extremely irritating.  I spent my day off trying to track this down and my sym link went to an old copy.  Closing.
