### ISSUE TITLE
Unit error in Erosion module

### ISSUE THREAD

**Issue by NSPECT** [NOAA-OCM/QNSPECT#70]
If you perform a run of the erosion module, then look at the top cell of a watershed, you will notice that both local and accumulated values are the same.  This is not correct, since local should be in Kilograms and accumulated should be in Megagrams. One of these is off by a factor of 1000.  I suspect it is the Accumulated value, but haven't worked out all the calculations by hand yet.

**Comment by jamie-carter** [comment]
I noticed this as well. Also, the values in the Sediment Accumulation grid are very small, so small in fact that the range of values on the symbology scale are 0 on both the top and bottom (at least for my Hawaii test data).

![image](https://user-images.githubusercontent.com/99736415/155599509-f4d2adb8-00c0-44bd-b1f9-810905e409a6.png)

**Comment by ar-siddiqui** [comment]
> I noticed this as well. Also, the values in the Sediment Accumulation grid are very small, so small in fact that the range of values on the symbology scale are 0 on both the top and bottom (at least for my Hawaii test data).

Can you provide screenshots here please.

**Comment by NSPECT** [comment]
From base erosion run on HI_sample data:

![image](https://user-images.githubusercontent.com/99758014/160650163-537315f7-9f4e-4034-b499-1aa50687e341.png)
