### ISSUE TITLE
Align Rasters should use Clip Raster by Mask Layer rather than Clip Raster by Extent

### ISSUE THREAD

**Issue by shanburkhalter** [NOAA-OCM/QNSPECT#74]
### Latest QNSPECT version

- [X] I am running the latest QNSPECT version

### Similar issue do not exist

- [X] I have searched existing issues to make sure a similar issue does not exist

### What is the bug or the crash?

QNSPECT users almost always are working within a defined area of interest such as a polygon watershed basin. Align Rasters currently clips by corner coordinates providing a rectangular output. If **Clip Raster by Mask Layer** could be used in Align Rasters the output would be based on the shape of the area of interest. 

### Steps to reproduce the issue

Go to Align Rasters
Add reference Raster and Rasters to Align
Add a polygon vector file as the Clipping Extent

### Versions

QGIS version
3.22.3-Białowieża

**Comment by ar-siddiqui** [comment]
There are mask by layer algorithms available in QGIS. A user can use them on inputs or outputs of `align rasters` tool to get desired behaviour, but I agree this would be a good feature to add.
