### ISSUE TITLE
Hydrologic Soils misspelled in tools

### ISSUE THREAD

**Issue by jamie-carter** [NOAA-OCM/QNSPECT#75]
### Latest QNSPECT version

- [X] I am running the latest QNSPECT version

### Similar issue do not exist

- [X] I have searched existing issues to make sure a similar issue does not exist

### What is the bug or the crash?

Not a bug per se, but the Hydrologic Soils are spelled as _Hydrographic_ Soils throughout the tools.

### Steps to reproduce the issue

Noticeable in Run Erosion Analysis and Run Pollution Analysis tools, both for the raster dropdown and in the help. Possibly elsewhere too.

### Versions

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 1909

Active Python plugins
curve_number_generator
1.3
mapswipetool_plugin
1.2
QNSPECT
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

**Comment by NSPECT** [comment]
Fixed NSPECT/QNSPECT dle_work branch, commit 3c4d157e70d53a9e665c87f45f235c9643ba54ba
