### ISSUE TITLE
Change the name for the “Desired Outputs [optional]” group in Pollution Analysis tool

### ISSUE THREAD

**Issue by jamie-carter** [NOAA-OCM/QNSPECT#79]
### Latest QNSPECT version

- [X] I am running the latest QNSPECT version

### Similar requests do not exist

- [X] I have searched existing issues to make sure a similar request does not exist

### Feature description

Let’s change the name for the “Desired Outputs [optional]” group in the Run Pollution Analysis tool to something like “Pollutant Outputs [optional]”. This is really what people are looking to generate, and I totally missed it the first few times trying to run the tool. If possible, it would be good to make it very clear what this is, and that it must be selected in order to generate outputs.

**Comment by NSPECT** [comment]
Fixed in NSPECT/QNSPECT dle_work branch, commit 5f7b0b83f8cf0a6b848898ce2fe0b7e837fee745

**Comment by ar-siddiqui** [comment]
@NSPECT  @DaveEslinger 
The initial thought behind calling it `Desired Outputs` was that it has runoff output as well which is not a pollutant? Are we fine with calling it `Desired Pollutant` despite that?
We can make it non-optional to make it more clear that is required.

**Comment by DaveEslinger** [comment]
We definitely need to make it more apparent that this is where one specifies the desired pollutants.  You may recall that, like Jamie, I missed it my first several times running the tool and had to ask when the pollutant aspects would be implemented.

I think calling it pollutants and making it non-optional will help.  Maybe change the label to "Define runoff and pollutant outputs"  and remove the optional setting.  I'm also not too concerned about having runoff listed and calling it a pollutant.

**Comment by ar-siddiqui** [comment]
> We definitely need to make it more apparent that this is where one specifies the desired pollutants. You may recall that, like Jamie, I missed it my first several times running the tool and had to ask when the pollutant aspects would be implemented.
> 
> I think calling it pollutants and making it non-optional will help. Maybe change the label to "Define runoff and pollutant outputs" and remove the optional setting. I'm also not too concerned about having runoff listed and calling it a pollutant.

Sounds good. Can you change the optional to `False` and make the name change here as well

https://github.com/NSPECT/QNSPECT/blob/d06d4a54b3dbb331dee3487e99ad00f87feb3eb4/algorithms/compare_scenarios/compare_pollution.py#L123

I can't contribute to NSPECT/dev branch directly.
