### ISSUE TITLE
Raster colors not loading consistently

### ISSUE THREAD

**Issue by NSPECT** [NOAA-OCM/QNSPECT#82]
### Latest QNSPECT version

- [X] I am running the latest QNSPECT version

### Similar issues do not exist

- [X] I have searched existing issues to make sure a similar issue does not exist

### What is the bug or the crash?

Output from Analysis routines do not consistently load the correct color tables.  Typical error warnings seem to be:
"2022-03-22T10:46:13     CRITICAL    ERROR 6: C:\Users\davee\AppData\Local\Temp\processing_pVfCXl\2a143c83a76741c4953606acf6b98cdf\accumulation.tif, band 1: SetColorTable() only supported for Byte or UInt16 bands in TIFF format." and

2022-03-22T10:46:13     CRITICAL    WARNING: Too many values, color table cut to 65535 entries

I don't these are related, but they seem to be what show up.  I say that because in back-to-back runs, the first run (with all18 possible pollutant output raster) only 1 raster was colored, in the second one all were colored correctly.

### Steps to reproduce the issue

Run Pollutant analysis.  See if all rasters get consistent (non-QGIS gray) color ramps.  Try it again.  It seems arbitrary.

### Screenshots and Attachements

Correct colors mapping, all the same nutrients get the same color ramp, i.e., all Lead rasters are red, so only one of each is shown:
<img width="198" alt="Correct_colors" src="https://user-images.githubusercontent.com/99758014/159523518-cc178a40-b714-4452-a815-313311516387.png">

No colors loaded, default gray colors:
<img width="211" alt="default_bad_colors" src="https://user-images.githubusercontent.com/99758014/159523594-6ccd27d4-a906-42c9-bd13-5f5c608da376.png">

### Versions

QGIS version
3.20.3-Odense
QGIS code revision
495fbaec
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.1
EPSG Registry database version
v10.018 (2021-04-02)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
curve_number_generator
daves_proc
debug_vs
pluginbuilder3
plugin_reloader
QNSPECT
valuetool
db_manager
MetaSearch
processing

### Additional context

We've talked about this, but I don't think it is documented as an issue.

**Comment by ar-siddiqui** [comment]
Possible duplicate of #64

**Comment by ar-siddiqui** [comment]
These two issues might not be caused by the same underlying function/class because Dave got some outputs that have colors but no units.

> Possible duplicate of #64

**Comment by ar-siddiqui** [comment]
An issue is filed with QGIS.

https://github.com/qgis/QGIS/issues/48087

**Comment by ar-siddiqui** [comment]
An issue is filed with QGIS.

https://github.com/qgis/QGIS/issues/48087
